#ifndef HUD_LOGO_H
#define HUD_LOGO_H

#include "hud.h"
#include "mode.h"

/*
 * Static miniature of the title Zanac MD mark for the Original dashboard.
 * Generated by tools/build_hud_logo.py from res/title_md_logo.png.
 * 6x2 tiles, PAL3 TMS nibbles (color 0 transparent).
 *
 * Pocket: WINDOW cols 25-30, MSX rows 22-23 (screen rows 24-25) — the
 * empty interior above / on the closing hbar, under FIRE, clear of TIME.
 */
#define HUD_LOGO_TILE_W     6
#define HUD_LOGO_TILE_H     2
#define HUD_LOGO_TILES      (HUD_LOGO_TILE_W * HUD_LOGO_TILE_H)
#define HUD_LOGO_MSX_ROW    22
#define HUD_LOGO_COL        (MODE_BAR_COL + 1)
#define HUD_LOGO_VDP        (HUD_TILE_BASE + 256)

extern const u8 hud_logo_tiles[HUD_LOGO_TILES * 32];

#endif
