#ifndef HUD_LOGO_H
#define HUD_LOGO_H

#include "hud.h"
#include "mode.h"

/*
 * Static miniature of the title Zanac MD mark for the Original dashboard.
 * Generated by tools/build_hud_logo.py from res/title_md_logo.png.
 * Clipped/regenerated from the good #121 6x2 / title_md_logo.png:
 * Zanac is the 6x2 top row squeezed to 4 tiles; MD is the title
 * red/green mark in 2 tiles (not the broken #119 all-blue bbox).
 * PAL3 TMS nibbles (color 0 transparent).
 *
 * Pocket: WINDOW cols 25-30, MSX row 17 (screen row 19). 6x2 cannot sit
 * above FIRE: 16-17 hits the ROUND digit, 18-19 is FIRE. Row 17 is the
 * empty 0x4BDF strip between ROUND (15-16) and FIRE (18-19). Zanac 4
 * tiles + MD 2 tiles. 0x4BDF 03 sides stay. TIME at MSX 21 no longer
 * overlaps; clear restores the border row, not this mark.
 */
#define HUD_LOGO_TILE_W     6
#define HUD_LOGO_TILE_H     1
#define HUD_LOGO_TILES      (HUD_LOGO_TILE_W * HUD_LOGO_TILE_H)
#define HUD_LOGO_MSX_ROW    17
#define HUD_LOGO_COL        (MODE_BAR_COL + 1)
#define HUD_LOGO_VDP        (HUD_TILE_BASE + 256)

/* u32, not u8: VDP_loadTileData long-reads the source. A u8 blob can
 * start odd and the 68000 takes Address error (same class as s_orb_cache). */
extern const u32 hud_logo_tiles[HUD_LOGO_TILES * 8];

#endif
