#ifndef HUD_LOGO_H
#define HUD_LOGO_H

#include "hud.h"
#include "mode.h"

/*
 * Static miniature of the title Zanac MD mark for the Original dashboard.
 * Generated by tools/build_hud_logo.py from res/title_md_logo.png.
 * 6x2 tiles, PAL3 TMS nibbles (color 0 transparent).
 *
 * Pocket: WINDOW cols 25-30, MSX rows 21-22 (screen rows 23-24).
 * Raised one 8px / MD-band row from the old 22-23 seat so the mark
 * sits above the closing hbar (MSX 23). FIRE is MSX 18-19; TIME at
 * MSX 21 paints over the ZANAC band when live, then restamps.
 */
#define HUD_LOGO_TILE_W     6
#define HUD_LOGO_TILE_H     2
#define HUD_LOGO_TILES      (HUD_LOGO_TILE_W * HUD_LOGO_TILE_H)
#define HUD_LOGO_MSX_ROW    21
#define HUD_LOGO_COL        (MODE_BAR_COL + 1)
#define HUD_LOGO_VDP        (HUD_TILE_BASE + 256)

/* u32, not u8: VDP_loadTileData long-reads the source. A u8 blob can
 * start odd and the 68000 takes Address error (same class as s_orb_cache). */
extern const u32 hud_logo_tiles[HUD_LOGO_TILES * 8];

#endif
